channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pandas-profiling==2.9.0
  - ipywidgets
  - hyperopt
  - kaggle
  - plotly
  - scikit-learn=0.24.0
  - scipy
  - numpy
  - python=3.7.5
  - py-xgboost
  - jupyterlab
  - nb_conda
  - bokeh
  - pandas
  - holoviews=1.14.1
  - seaborn
